//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Clicker.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Clicker: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Clicker()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Clicker"",
    ""maps"": [
        {
            ""name"": ""MouseL"",
            ""id"": ""d7814941-c379-4ee9-87dc-7d0d537e1e45"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""6420cc3b-55a9-4161-bed6-5beb74e31d98"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""86ace0ad-c32d-455b-98b1-2a25d01629a9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MouseL
        m_MouseL = asset.FindActionMap("MouseL", throwIfNotFound: true);
        m_MouseL_Click = m_MouseL.FindAction("Click", throwIfNotFound: true);
    }

    ~@Clicker()
    {
        UnityEngine.Debug.Assert(!m_MouseL.enabled, "This will cause a leak and performance issues, Clicker.MouseL.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MouseL
    private readonly InputActionMap m_MouseL;
    private List<IMouseLActions> m_MouseLActionsCallbackInterfaces = new List<IMouseLActions>();
    private readonly InputAction m_MouseL_Click;
    public struct MouseLActions
    {
        private @Clicker m_Wrapper;
        public MouseLActions(@Clicker wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_MouseL_Click;
        public InputActionMap Get() { return m_Wrapper.m_MouseL; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseLActions set) { return set.Get(); }
        public void AddCallbacks(IMouseLActions instance)
        {
            if (instance == null || m_Wrapper.m_MouseLActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MouseLActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
        }

        private void UnregisterCallbacks(IMouseLActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
        }

        public void RemoveCallbacks(IMouseLActions instance)
        {
            if (m_Wrapper.m_MouseLActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMouseLActions instance)
        {
            foreach (var item in m_Wrapper.m_MouseLActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MouseLActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MouseLActions @MouseL => new MouseLActions(this);
    public interface IMouseLActions
    {
        void OnClick(InputAction.CallbackContext context);
    }
}
